---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-kustomization
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./app
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-source
