---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: socks-kustomization
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: socks-source
